                                                # Automated Response System (Linux)
                                                
                                                
                                        # This script automatically blocks suspicious IPs using iptables
                                        # and logs the action for auditing purposes

import os  # Import os module to run Linux commands from Python

# Example list of suspicious IPs (this can be replaced by your blocked_ips.txt)
suspicious_ips = ["192.168.1.23", "10.0.0.5"]  

# Loop through each suspicious IP and block it
for ip in suspicious_ips:
    # Block the IP using iptables
    os.system(f"sudo iptables -A INPUT -s {ip} -j DROP")  # Add rule to drop incoming traffic from the IP

    # Log the blocked IP to a file for auditing
    with open("/var/log/ids_alerts.log", "a") as log_file:
        log_file.write(f"Blocked IP: {ip}\n")  # Append the blocked IP to the log file

    # Print info to console
    print(f"[INFO] IP {ip} blocked and logged.")


# Another way: Block IPs directly from the "blocked_ips.txt" file
import os  # Already imported above, redundant here but harmless

# Read blocked IPs from the file generated by IDS
with open("blocked_ips.txt", "r") as file:        
    ips = file.readlines()  # Read all IPs into a list

# Loop through each IP and block it
for ip in ips:
    ip = ip.strip()  # Remove any newline characters

    print(f"Blocking IP: {ip}")  # Info to console

    # Block the IP using iptables
    os.system(f"sudo iptables -A INPUT -s {ip} -j DROP")  # Add firewall rule

    # Log the blocked IP
    with open("ids_alerts.log", "a") as log:  # Open log file in append mode
        log.write(f"Blocked IP: {ip}\n")  # Write the blocked IP
 
                          