                                                 #Intrusion Detection System (IDS)  #Attack Log Simulation
                            #Brute-force login         #Port scanning     #other untrusted attempts 


from collections import defaultdict  # Import defaultdict to easily count occurrences and manage sets

LOG_FILE = "network_logs.log"  # The log file generated by the previous script

# Dictionaries to keep track of failed logins and accessed ports per IP
failed_logins = defaultdict(int)  # Count of failed login attempts per IP
port_access = defaultdict(set)    # Set of accessed ports per IP
suspicious_ips = set()            # Set to store IPs flagged as suspicious

# Thresholds for detecting attacks
BRUTE_FORCE_THRESHOLD = 5  # If an IP has 5 or more failed logins, flag it
PORT_SCAN_THRESHOLD = 4    # If an IP accesses 4 or more different ports, flag it

# Read the log file line by line
with open(LOG_FILE, "r") as file:
    for line in file:
        parts = line.strip().split(" | ")  # Split the log line into components
        ip = parts[1].split("=")[1]       # Extract IP address
        port = parts[2].split("=")[1]     # Extract port number
        status = parts[3].split("=")[1]   # Extract status (SUCCESS or FAILED)

        # Track failed login attempts
        if status == "FAILED":
            failed_logins[ip] += 1        # Increment count for this IP

        # Track accessed ports
        port_access[ip].add(port)         # Add port to the set of accessed ports

# Detect brute-force attacks
for ip in failed_logins:
    if failed_logins[ip] >= BRUTE_FORCE_THRESHOLD:
        suspicious_ips.add(ip)           # Add IP to suspicious list
        print(f"[ALERT] Brute-force detected from {ip}")  # Alert message

# Detect port scanning
for ip in port_access:
    if len(port_access[ip]) >= PORT_SCAN_THRESHOLD:
        suspicious_ips.add(ip)           # Add IP to suspicious list
        print(f"[ALERT] Port scanning detected from {ip}")  # Alert message

# Save suspicious IPs to a file for potential automated response
with open("blocked_ips.txt", "w") as f:
    for ip in suspicious_ips:
        f.write(ip + "\n")               # Write each suspicious IP on a new line



                                        
                                        
